version: '3.8'

services:
  backend:
    build: ./django_app
    restart: always
    command: bash -c "
      sleep 1m &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py createsuperuser --noinput --userid ${DJANGO_ADMIN_ID} --password ${DJANGO_ADMIN_PASSWORD} --nickname ${DJANGO_ADMIN_NICKNAME} --email ${DJANGO_ADMIN_EMAIL} ;
      gunicorn --certfile=/etc/letsencrypt/live/kmj36.duckdns.org/fullchain.pem --keyfile=/etc/letsencrypt/live/kmj36.duckdns.org/privkey.pem --bind 0.0.0.0:${DJANGO_PORT} django_app.wsgi:application"
    container_name: ${CONTAINER_NAME}_django_backend
    volumes:
      - ./db.sqlite3:/TestDjango/db.sqlite3
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT} # HOST:CONTAINER
    environment:
      DJANGO_DEBUG_MODE: ${DJANGO_DEBUG_MODE}
      DJANGO_ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DJANGO_ADMIN_ID: ${DJANGO_ADMIN_ID}
      DJANGO_ADMIN_PASSWORD: ${DJANGO_ADMIN_PASSWORD}
      DJANGO_ADMIN_NICKNAME: ${DJANGO_ADMIN_NICKNAME}
      DJANGO_ADMIN_EMAIL: ${DJANGO_ADMIN_EMAIL}
      DJANGO_PRIVATE_API_MODE: ${DJANGO_PRIVATE_API_MODE}
      PRIVATE_API_AES_ENCRYPTION_KEY: ${PRIVATE_API_AES_ENCRYPTION_KEY}
    networks:
      - BackNet

  web:
    image: nginx:latest
    restart: always
    container_name: ${CONTAINER_NAME}_nginx_web
    ports:
      - ${NGINX_PORT}:80 # HOST:CONTAINER
    volumes:
      - ./nginx_webapp/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_webapp/intropage-app/build:/usr/share/nginx/html/
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - intropageNet

  admin:
    image: nginx:latest
    restart: always
    container_name: ${CONTAINER_NAME}_nginx_admin
    ports:
      - ${ADMIN_PORT}:80 # HOST:CONTAINER
    volumes:
      - ./nginx_webapp/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_webapp/cms/build:/usr/share/nginx/html/
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - intropageNet

networks:
  intropageNet:
    driver: bridge
  BackNet:
    driver: bridge