class literals:
    SUCCESS = "Success"
    ERROR = "Error"
    
    NOTFOUND_RESPONSE = "요청한 리소스를 찾을 수 없습니다."
    FORBIDDEN_RESPONSE = "접근 권한이 없습니다."
    NOCONTENT_RESPONSE = "리스트가 비어 있습니다."
    LIST_RESPONSE = "리스트 조회되었습니다."
    INFO_RESPONSE = "정보 조회되었습니다."
    LOGIN_SUCCESS = "로그인에 성공하였습니다."
    LOGIN_FAILED = "로그인에 실패하였습니다."
    AUTH_SUCCESS = "인증에 성공하였습니다."
    AUTH_FAILED = "인증에 실패하였습니다."
    DELETE_SUCCESS = "정보가 삭제되었습니다."
    VALID_REQUEST = "유효한 요청입니다."
    INVALID_REQUEST = "유효하지 않은 요청입니다."
    REGISTER_SUCCESS = "회원가입에 성공하였습니다."
    REGISTER_FAILED = "회원가입에 실패하였습니다."
    CREATE_SUCCESS = "정보가 생성되었습니다."
    MODIFY_SUCCESS = "정보가 변경되었습니다."
    CANNOTDELETE_SUPERUSER = "최초 관리자 계정은 삭제할 수 없습니다."
    CANNOTMODIFY_SUPERUSER = "최초 관리자 계정은 수정할 수 없습니다."
    REQUIRED_FIELD = "필수 입력값이 누락되었습니다."