# Generated by Django 4.2.3 on 2023-07-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
