# Generated by Django 4.2.3 on 2023-07-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='category',
            name='madeby',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='madeby',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
