# Generated by Django 4.2.3 on 2023-07-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_remove_user_is_staff_alter_category_madeby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
