# Generated by Django 4.2.3 on 2023-07-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_tag_tagname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
