# Generated by Django 4.2.3 on 2023-07-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
