# Generated by Django 4.2.3 on 2023-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_remove_category_madeby_remove_comment_secrected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='User Email'),
        ),
    ]
