# Generated by Django 4.2.3 on 2023-08-17 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Category Creator'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Comment Creator'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.category', verbose_name='Post Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Post Creator'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tag Creator'),
        ),
    ]
