# Generated by Django 4.2.3 on 2023-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_alter_category_userid_alter_comment_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='secret_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Secret Password'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryname',
            field=models.CharField(max_length=64, unique=True, verbose_name='Category Name'),
        ),
    ]
