# Generated by Django 4.2.3 on 2023-08-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_alter_post_content_alter_post_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1024, verbose_name='Comment Content'),
        ),
    ]
