# Generated by Django 4.2.3 on 2023-09-18 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comment Creator'),
        ),
        migrations.AlterField(
            model_name='post',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post Creator'),
        ),
        migrations.CreateModel(
            name='UserReportDetail',
            fields=[
                ('reportid', models.AutoField(primary_key=True, serialize=False, verbose_name='Report ID')),
                ('reportreason', models.CharField(max_length=128, verbose_name='Report Reason')),
                ('reportat', models.DateTimeField(auto_now_add=True)),
                ('evidence_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Evidence Type')),
                ('evidence_targetid', models.IntegerField(verbose_name='Evidence Target ID')),
                ('evidence_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Evidence URL')),
                ('targetid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reporter ID')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserBanDetail',
            fields=[
                ('banid', models.AutoField(primary_key=True, serialize=False, verbose_name='Ban ID')),
                ('bannedreason', models.CharField(max_length=128, verbose_name='Block Reason')),
                ('bannedat', models.DateTimeField(auto_now_add=True)),
                ('banreleaseat', models.DateTimeField(blank=True, null=True)),
                ('bannedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Blocker ID')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banneduser', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
        ),
        migrations.CreateModel(
            name='ForcedControl',
            fields=[
                ('controlid', models.AutoField(primary_key=True, serialize=False, verbose_name='Control ID')),
                ('contenttype', models.CharField(max_length=32, verbose_name='Content Type')),
                ('contentid', models.IntegerField(verbose_name='Content ID')),
                ('reason', models.CharField(max_length=128, verbose_name='Reason')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('adminid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Admin ID')),
                ('targetid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL, verbose_name='Target ID')),
            ],
        ),
    ]
