# Generated by Django 4.2.3 on 2023-09-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_alter_comment_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbandetail',
            old_name='banreleaseat',
            new_name='banneduntil',
        ),
    ]
