# Generated by Django 4.2.3 on 2023-09-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0031_rename_banreleaseat_userbandetail_banneduntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcedcontrol',
            name='contentid',
            field=models.CharField(max_length=32, verbose_name='Content ID'),
        ),
    ]
