# Generated by Django 4.2.3 on 2023-09-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_alter_forcedcontrol_contentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcedcontrol',
            name='targetid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to=settings.AUTH_USER_MODEL, verbose_name='Target ID'),
        ),
    ]
