# Generated by Django 4.2.3 on 2023-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_alter_forcedcontrol_targetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnailurl',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Thumbnail URL'),
        ),
    ]
