# Generated by Django 4.2.3 on 2023-10-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_post_thumbnailurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categorydescription',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Category Description'),
        ),
    ]
