# Generated by Django 4.2.3 on 2023-10-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_category_categorydescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryname',
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Tag ID'),
        ),
    ]
