# Generated by Django 4.2.3 on 2023-10-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_remove_category_categoryname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tagname',
        ),
    ]
