# Generated by Django 4.2.3 on 2023-10-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0037_remove_tag_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnailurl',
            field=models.TextField(blank=True, max_length=65535, null=True, verbose_name='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Tag Name'),
        ),
    ]
