# Generated by Django 4.2.3 on 2023-10-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0039_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnailurl',
            field=models.TextField(blank=True, default='', max_length=65535, verbose_name='Thumbnail URL'),
        ),
    ]
