# Generated by Django 4.2.3 on 2023-10-22 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0041_alter_post_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.category', verbose_name='Post Category'),
        ),
    ]
