# Generated by Django 4.2.3 on 2023-11-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0042_alter_post_categoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_ip',
            field=models.CharField(max_length=16, null=True, verbose_name='Comment Creator IP'),
        ),
    ]
