# Generated by Django 4.2.3 on 2023-11-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0043_comment_created_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.post', verbose_name='Comment Post ID'),
        ),
    ]
