# Generated by Django 4.2.3 on 2023-12-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0044_alter_comment_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
            ],
        ),
    ]
